# Docker-based Testing Environment
# Use this for complete isolation between test users

version: '3.8'

services:
  # Main application
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///instance/securedeal_dev.db
    volumes:
      - .:/app
      - ./instance:/app/instance
    depends_on:
      - blockchain-service
    networks:
      - securedeal-network

  # Blockchain service
  blockchain-service:
    build:
      context: ./smart-contract-to-implement/blockchain_services
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - securedeal-network

  # Payment monitor
  payment-monitor:
    build: .
    command: python3 payment_monitor.py
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///instance/securedeal_dev.db
    volumes:
      - .:/app
      - ./instance:/app/instance
    depends_on:
      - app
      - blockchain-service
    networks:
      - securedeal-network

  # Browser testing containers (for complete isolation)
  browser-user1:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
      - "7900:7900"  # VNC port for viewing
    environment:
      - SE_SCREEN_WIDTH=1920
      - SE_SCREEN_HEIGHT=1080
    networks:
      - securedeal-network

  browser-user2:
    image: selenium/standalone-chrome:latest
    ports:
      - "4445:4444"
      - "7901:7900"  # VNC port for viewing
    environment:
      - SE_SCREEN_WIDTH=1920
      - SE_SCREEN_HEIGHT=1080
    networks:
      - securedeal-network

networks:
  securedeal-network:
    driver: bridge

volumes:
  app-data:
